

semantic_types <-
        c('Machine Activity',
'Conceptual Entity',
'Body Space or Junction',
'Medical Device',
'Molecular Function',
'Health Care Related Organization',
'Research Activity',
'Immunologic Factor',
'Activity',
'Amino Acid Sequence',
'Anatomical Abnormality',
'Chemical',
'Disease or Syndrome',
'Receptor',
'Event',
'Classification',
'Social Behavior',
'Pharmacologic Substance',
'Carbohydrate Sequence',
'Professional or Occupational Group',
'Plant',
'Therapeutic or Preventive Procedure',
'Clinical Drug',
'Anatomical Structure',
'Nucleic Acid, Nucleoside, or Nucleotide',
'Fungus',
'Physiologic Function',
'Professional Society',
'Biologically Active Substance',
'Embryonic Structure',
'Age Group',
'Genetic Function',
'Mental Process',
'Research Device',
'Organism Attribute',
'Physical Object',
'Fully Formed Anatomical Structure',
'Health Care Activity',
'Cell Function',
'Drug Delivery Device',
'Language',
'Functional Concept',
'Bird',
'Gene or Genome',
'Regulation or Law',
'Quantitative Concept',
'Hormone',
'Eukaryote',
'Clinical Attribute',
'Hazardous or Poisonous Substance',
'Food',
'Geographic Area',
'Intellectual Product',
'Body Substance',
'Biologic Function',
'Mental or Behavioral Dysfunction',
'Temporal Concept',
'Mammal',
'Organism Function',
'Body System',
'Neoplastic Process',
'Patient or Disabled Group',
'Vitamin',
'Antibiotic',
'Self-help or Relief Organization',
'Governmental or Regulatory Activity',
'Cell Component',
'Molecular Sequence',
'Idea or Concept',
'Virus',
'Reptile',
'Cell or Molecular Dysfunction',
'Organization',
'Acquired Abnormality',
'Manufactured Object',
'Entity',
'Daily or Recreational Activity',
'Laboratory Procedure',
'Substance',
'Pathologic Function',
'Indicator, Reagent, or Diagnostic Aid',
'Group Attribute',
'Congenital Abnormality',
'Tissue',
'Organ or Tissue Function',
'Organic Chemical',
'Family Group',
'Inorganic Chemical',
'Chemical Viewed Functionally',
'Animal',
'Phenomenon or Process',
'Finding',
'Group',
'Vertebrate',
'Experimental Model of Disease',
'Sign or Symptom',
'Body Location or Region',
'Organism',
'Individual Behavior',
'Population Group',
'Amphibian',
'Biomedical or Dental Material',
'Enzyme',
'Spatial Concept',
'Bacterium',
'Qualitative Concept',
'Occupational Activity',
'Laboratory or Test Result',
'Fish',
'Diagnostic Procedure',
'Human-caused Phenomenon or Process',
'Environmental Effect of Humans',
'Educational Activity',
'Molecular Biology Research Technique',
'Archaeon',
'Amino Acid, Peptide, or Protein',
'Nucleotide Sequence',
'Behavior',
'Element, Ion, or Isotope',
'Injury or Poisoning',
'Natural Phenomenon or Process',
'Occupation or Discipline',
'Human',
'Biomedical Occupation or Discipline',
'Body Part, Organ, or Organ Component',
'Cell',
'Chemical Viewed Structurally')
#conn <- chariot::connectAthena()

for (i in 38:length(semantic_types)) {

        semantic_type <- semantic_types[i]

        x <-
        pg13::query(conn = conn,
                    sql_statement = SqlRender::render(
                                                "
                                                with cui_sample AS (
                                                SELECT DISTINCT m.cui
                                                FROM mth.mrsty s
                                                LEFT JOIN mth.mrconso m
                                                ON m.cui = s.cui
                                                WHERE s.sty = '@semantic_type'
                                    )
                                    SELECT m.*
                                    FROM cui_sample
                                    LEFT JOIN mth.mrconso m
                                    ON m.cui = cui_sample.cui
                                    WHERE m.lat = 'ENG';",
                                        semantic_type = semantic_type)) %>%
                                dplyr::group_by(cui) %>%
                                dplyr::summarize_at(vars(str), function(x) paste(unique(tolower(x)), collapse = ", "))

                print(semantic_type)
                print(x)

                secretary::press_enter()
}



sty_to_domain_id <-
        function() {

                tibble::tribble(~sty, ~domain_id,
                                'Machine Activity', NA,
                                'Conceptual Entity', NA,
                                'Body Space or Junction', "Observation",
                                'Medical Device', "Device",
                                'Molecular Function', "Observation",
                                'Health Care Related Organization', "Observation",
                                'Research Activity', "Observation",
                                'Immunologic Factor',"Observation",
                                'Activity',NA,
                                'Amino Acid Sequence', "Observation",
                                'Anatomical Abnormality', "Observation",
                                'Chemical', "Drug",
                                'Disease or Syndrome', "Observation",
                                'Receptor', "Observation",
                                'Event', "Observation",
                                # 'Classification', classification concepts across domains
                                'Social Behavior', "Observation",
                                'Pharmacologic Substance', "Drug",
                                'Carbohydrate Sequence', NA,
                                'Professional or Occupational Group',"Observation",
                                'Plant', NA,
                                'Therapeutic or Preventive Procedure', "Procedure",
                                'Clinical Drug', "Drug",
                                'Anatomical Structure', "Observation",
                                'Nucleic Acid, Nucleoside, or Nucleotide', "Observation",
                                'Fungus', NA,
                                'Physiologic Function', "Condition",
                                'Professional Society', NA,
                                'Biologically Active Substance', "Drug",
                                'Embryonic Structure', "Observation",
                                'Age Group', "Observation",
                                'Genetic Function', "Observation",
                                'Mental Process', "Observation",
                                'Research Device', "Device",
                                'Organism Attribute', "Measurement",
                                'Physical Object', NA,
                                'Fully Formed Anatomical Structure', "Observation",
                                'Health Care Activity', NA,
                                'Cell Function', "Observation",
                                'Drug Delivery Device', "Device",
                                'Language', "Observation",
                                'Functional Concept', "Observation",
                                'Bird', NA,
                                'Gene or Genome', "Observation",
                                'Regulation or Law', NA,
                                'Quantitative Concept', "Measurement",
                                'Hormone', "Observation",
                                'Eukaryote', NA,
                                # Overlap
                                'Clinical Attribute', "Observation",
                                'Clinical Attribute', "Measurement",
                                'Hazardous or Poisonous Substance', "Drug",
                                'Food', "Observation",
                                'Geographic Area', "Observation",
                                'Intellectual Product', "Observation",
                                'Body Substance', "Observation",
                                'Biologic Function', "Observation",
                                'Mental or Behavioral Dysfunction', "Observation",
                                'Temporal Concept', "Observation",
                                'Mammal', NA,
                                'Organism Function', "Observation",
                                'Body System', "Observation",
                                'Neoplastic Process', "Observation",
                                'Patient or Disabled Group', NA,
                                'Vitamin', "Drug",
                                'Antibiotic', "Drug",
                                'Self-help or Relief Organization', NA,
                                'Governmental or Regulatory Activity', "Observation",
                                'Cell Component', "Observation",
                                'Molecular Sequence', "Observation",
                                'Idea or Concept', NA,
                                'Virus', "Observation",
                                'Reptile', NA,
                                'Cell or Molecular Dysfunction', "Observation",
                                'Organization',NA,
                                'Acquired Abnormality', "Observation",
                                'Manufactured Object', NA,
                                'Entity', NA,
                                'Daily or Recreational Activity',
                                'Laboratory Procedure',
                                'Substance',
                                'Pathologic Function',
                                'Indicator, Reagent, or Diagnostic Aid',
                                'Group Attribute',
                                'Congenital Abnormality',
                                'Tissue',
                                'Organ or Tissue Function',
                                'Organic Chemical',
                                'Family Group',
                                'Inorganic Chemical',
                                'Chemical Viewed Functionally',
                                'Animal',
                                'Phenomenon or Process',
                                'Finding',
                                'Group',
                                'Vertebrate',
                                'Experimental Model of Disease',
                                'Sign or Symptom',
                                'Body Location or Region',
                                'Organism',
                                'Individual Behavior',
                                'Population Group',
                                'Amphibian',
                                'Biomedical or Dental Material',
                                'Enzyme',
                                'Spatial Concept',
                                'Bacterium',
                                'Qualitative Concept',
                                'Occupational Activity',
                                'Laboratory or Test Result',
                                'Fish',
                                'Diagnostic Procedure',
                                'Human-caused Phenomenon or Process',
                                'Environmental Effect of Humans',
                                'Educational Activity',
                                'Molecular Biology Research Technique',
                                'Archaeon',
                                'Amino Acid, Peptide, or Protein',
                                'Nucleotide Sequence',
                                'Behavior',
                                'Element, Ion, or Isotope',
                                'Injury or Poisoning',
                                'Natural Phenomenon or Process',
                                'Occupation or Discipline',
                                'Human',
                                'Biomedical Occupation or Discipline',
                                'Body Part, Organ, or Organ Component',
                                'Cell',
                                'Chemical Viewed Structurally')
        }
